FROM node:latest

# RUN npm install gulp -g
# docker run -i --rm -v /home/rob/repos/swp2/authorentool/:/src -p 4001:4001 -t authorentool /bin/bash
# docker run -it --rm --name authorentool -v "$PWD":/usr/src/authorentool -w /usr/src/authorentool -p 4001:4001 node:latest

# COPY . /src
# WORKDIR /src

# RUN npm install
# RUN ./node_modules/bower/bin/bower --allow-root --config.interactive=false


# replace this with your application's default port
# EXPOSE 4001 
# CMD ["gulp"]
